apiVersion: v1
kind: Template
metadata:
  name: revealjs
  annotations:
    description: "The HTML Presentation Framework"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
    labels:
      app: revealjs
    name: revealjs-${PRESENTATION_NAME}
  spec:
    replicas: 1
    selector:
      app: revealjs
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
        labels:
          app: revealjs
          deploymentconfig: revealjs
      spec:
        containers:
        - image: revealjs:latest
          name: revealjs
          ports:
          - containerPort: 8000
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - revealjs
        from:
          kind: ImageStreamTag
          name: revealjs:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      app: revealjs
    name: revealjs-${PRESENTATION_NAME}
  spec:
    ports:
    - name: 8000-tcp
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: revealjs
      deploymentconfig: revealjs-${PRESENTATION_NAME}
parameters:
- description: "The name of the collection of presentations"
  name: PRESENTATION_NAME
  required: true
- description: "The git repo hosting the collection of presentations"
  name: PRESENTATION_REPO
  required: true
- description: "The git reference you'd like to target"
  name: PRESENTATION_REF
  value: master
  required: true
